version: '3'

networks:
  integration-tests-example-test:
    driver: bridge

services:
  listd_tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    networks:
      - integration-tests-example-test
    volumes:
        - /Users/patrick/faxserver/:/go/src/github.com/TheTealLucky/faxserver/
  db:
    image: postgres:11.1
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: testdb
    restart: on-failure
    networks:
      - integration-tests-example-test
